### ISSUE TITLE
Add NSX License Usage information to NSX Manager documentation

### ISSUE THREAD

**Issue by HammadAlam** [vmware/nsx-powerops#101]
Currently the NSX-Manager excel sheet uses `Get-NSXLicense` to get license information however, this information is pulled from vCenter which does not track the NSX License usage, it only has the Total License allocated. The NSX Manager RestAPI (below) helps with this piece.

**We need to have input of both the Get-NSXLicense (EditionKey, License Key, Name, Total) and the API call below so the complete picture is painted.**

To get the usage information, following API has to be used

`$Request = https://<NSX_Mgr_IP>/api/2.0/services/licensing/capacityusage`

Which gives the below but does not include the vCenter or NSX Manager or License Key info. 

```
<?xml version="1.0" encoding="UTF-8"?>
<featureCapacityUsageList>
    <featureCapacityUsageInfo>
        <capacityUsageInfo>
            <capacityType>CPU_CAPACITY_TYPE</capacityType>
            <usageCount>12</usageCount>
        </capacityUsageInfo>
        <capacityUsageInfo>
            <capacityType>VM_CAPACITY_TYPE</capacityType>
            <usageCount>0</usageCount>
        </capacityUsageInfo>
        <capacityUsageInfo>
            <capacityType>CONCURRENT_USER_CAPACITY_TYPE</capacityType>
            <usageCount>0</usageCount>
        </capacityUsageInfo>
        <feature>vxlan</feature>
    </featureCapacityUsageInfo>
    <featureCapacityUsageInfo>
        <capacityUsageInfo>
            <capacityType>CPU_CAPACITY_TYPE</capacityType>
            <usageCount>12</usageCount>
        </capacityUsageInfo>
        <capacityUsageInfo>
            <capacityType>VM_CAPACITY_TYPE</capacityType>
            <usageCount>0</usageCount>
        </capacityUsageInfo>
        <capacityUsageInfo>
            <capacityType>CONCURRENT_USER_CAPACITY_TYPE</capacityType>
            <usageCount>0</usageCount>
        </capacityUsageInfo>
        <feature>dfw</feature>
    </featureCapacityUsageInfo>
</featureCapacityUsageList>
```

**Comment by HammadAlam** [comment]
In the Licensing output only keep the following from Get-NSXLicense

CostUnit
EditionKey
LicenseKey
Name
Total

In addition we need the usage information from the API mentioned in first comment

**Comment by thisispuneet** [comment]
Edit code to only show following fields from Get-NSXLicense command:
CostUnit, EditionKey, LicenseKey, Name, Total

Added code to show following fields from REST API call "https://<NSX_Mgr_IP>/api/2.0/services/licensing/capacityusage":
cpu_capacity_type, vm_capacity_type, concurrent_user_capacity_type (for all features like dfw, vxlan, etc).
