### ISSUE TITLE
Empty folders left under Reports directory

### ISSUE THREAD

**Issue by HammadAlam** [vmware/nsx-powerops#103]
When NSX-PowerOps starts, it creates a dated folder to put the data in. However, if the user did not actually run any report, the empty folder is left behind. Over time, this results in a lot of clutter with several empty folders. To resolve this we have one of two options:

a. [Preferred] Only create a folder when an option to run a Documentation or Healthcheck is chosen. If the user doesn't do either then there is no need to create a folder.

b. At exit, check if the folder is empty then delete it.

**Comment by thisispuneet** [comment]
Added code that checks if the folder is empty and then delete it.
