### ISSUE TITLE
Crash in menu 2 - 2 - 1 if there is no tunnel

### ISSUE THREAD

**Issue by ysi** [vmware/nsx-powerops#129]
Hi,

If you go to the menu 2 - 2 - 1 (Get Transport Node Tunnels) and NSX doesn't have any Tunnels, script crash. 
It's due if there is no tunnel. So in Json file the result_count = 0  and there is no parameters "tunnels".

Replacing the control based on len of the lenght of tunnel_json['tunnels'] by check if the parameter result_count is different to 0. If so, the get the len of tunnel_json['tunnels'] fix the issue.

        if tunnel_json['result_count'] != 0:
            x = (len(tunnel_json['tunnels']))
            for n  in range(x):
                print('Tunnel name: ',tunnel_json['tunnels'][n]['name'])
...

[EDIT]: another thing. The script crash on the same level, if Tunnel exist but if it's down and if some informations are missing. The script try print a missing key of tunnel_json. In my case, remote_node_id and remote_node_display_name are missing from the JSON.

I fix the issue like this :

        if tunnel_json['result_count'] != 0:
            x = (len(tunnel_json['tunnels']))
            for n  in range(x):
                if 'name' in  tunnel_json['tunnels'][n]: print('Tunnel name: ',tunnel_json['tunnels'][n]['name'])
                if 'status' in tunnel_json['tunnels'][n]: print('Tunnel Status: ',tunnel_json['tunnels'][n]['status'])
                if 'egress_interface' in tunnel_json['tunnels'][n]: print('Egress Interface: ',tunnel_json['tunnels'][n]['egress_interface'])
                if 'local_ip' in tunnel_json['tunnels'][n]: print('Local Tunnel IP: ',tunnel_json['tunnels'][n]['local_ip'])
                if 'remote_ip' in tunnel_json['tunnels'][n]: print('Remote Tunnel IP: ',tunnel_json['tunnels'][n]['remote_ip'])
                if 'remote_node_id' in  tunnel_json['tunnels'][n]: print('Remote Node ID: ',tunnel_json['tunnels'][n]['remote_node_id'])
                if 'remote_node_display_name' in  tunnel_json['tunnels'][n]: print('Remote Node: ',tunnel_json['tunnels'][n]['remote_node_display_name'])
                if 'encap' in  tunnel_json['tunnels'][n]: print('Tunnel Encapsulation: ',tunnel_json['tunnels'][n]['encap'])
                print('')
        else:
            print('**** No tunnels exist for this transport node ****')

[EDIT-2]: same thing must be done on docs_tn_tunnels.py (lines 131, 133, etc ...).

**Comment by domfoley** [comment]
tn_tunels scripts updated with exception handling.
