### ISSUE TITLE
Failure to remove a temporary file during processing

### ISSUE THREAD

**Issue by thisispuneet** [vmware/nsx-powerops#33]
Reported by @nmbradford 

```
Remove-Item : Cannot remove the item at 'C:\users\nick\Documents\git\NSX-PowerOps' because it is in use.
At C:\users\nick\Documents\git\NSX-PowerOps\nsx-PowerOps.ps1:376 char:9


        Remove-Item ./$nsxMgrCommandRouteTable
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


CategoryInfo          : InvalidOperation: (:) [Remove-Item], PSInvalidOperationException
FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.RemoveItemCommand
```

appears related to DLR route table query.  Suspect we could avoid the use of temporary files and build a hashtable instead.  Also, spotted use of redirection in invokeNSxCLI -> should leverage set-content rather than relying on external functionality to PowerShell.  Will look to refactor.

**Comment by HammadAlam** [comment]
The issue has been resolved in the code when the tool exits. However, if the tool is QUITted abruptly, the temporary files will not be deleted automatically.

WORKAROUND:
Remove the temp files manually.
