### ISSUE TITLE
Force a connection if not connected

### ISSUE THREAD

**Issue by HammadAlam** [vmware/nsx-powerops#35]
Once you start the tool and if you chose not to auto connect or it failed for some reason. We need a way from within the tool to kickstart connection again. 

In addition, if you are connected using a profile, but would like to connect using a different (non-default profile). There should be a way to switch the profile and connect using that without exiting.

May be we can add a #-4 in the Connection Profiles which says connect to selected profile. 

This can also be useful if from within the tool you want to disconnect and then connect to a new profile that was just created.

May be there is a way but is not obvious.

**Comment by thisispuneet** [comment]
Merging this to similar a ticket #64
