### ISSUE TITLE
Convert VIB test from SSH to esxcli

### ISSUE THREAD

**Issue by vmnomad** [vmware/nsx-powerops#39]
That will keep host access consistent across all health check tests

**Comment by HammadAlam** [comment]
@thisispuneet amd @vmnomad 
Can we close this now?

**Comment by vmnomad** [comment]
I believe it can be closed, but I would really appreciate it if you could test the updated scripts in your environments.

**Comment by HammadAlam** [comment]
I have tested it in couple of Environments and it all worked like a charm.

**Comment by HammadAlam** [comment]
Closing it. Will reopen if a user reports any issues.
