### ISSUE TITLE
DiagramNSX to expose filter field

### ISSUE THREAD

**Issue by thisispuneet** [vmware/nsx-powerops#44]
As discussed on the emails and feedback from RackSpace, can we expose some filtering mechanism to the input of the script.

TenantID is something that can be filtered on already but if we can expose it as an input when someone runs the script, would be great.

Secondly, if we can do exact samething as tenantID to Edge Name as so far customer feedback is that the ESG names usually carry some meaning especially in multi-tenant environments.

**Comment by HammadAlam** [comment]
We will leave it as is for now. Customers seem to be very happy with the current defaults. Will re-open if a similar customer request comes in. Also, we are hoping to reduce the number of interactive user inputs needed to run any documentation to support auto run of documents.
