### ISSUE TITLE
Add next steps commands as part of documentation for troubleshooting

### ISSUE THREAD

**Issue by thisispuneet** [vmware/nsx-powerops#46]
Feedback from customer Take Away:
a. Summaries are good
b. Help me with Next Steps

Customer requested a list of commands (next steps suggestion) to find more information about their environment. For ex, how to find VTEP Table or ARP Table etc. 

As the output of following commands are very dynamic, there is no value in dumping the output in the current Excel file. Instead, just guiding the customer with pre-populated commands is more useful as they don't have to figure out the commands and can just copy paste it to run.

List of commands for Hosts file:
- View VTEP Table
- View MAC Table
- View ARP Table
- Execute Ping
- May be do the same for pktcap-uw

**Comment by HammadAlam** [comment]
Closing it. Will review if more customers ask for it
