### ISSUE TITLE
DFW2Excel to include Redirect rules

### ISSUE THREAD

**Issue by HammadAlam** [vmware/nsx-powerops#51]
Currently we do not document Redirect rules. Feedback from field is that it would be very helpful to have that information documented.

@tonysangha

**Comment by tonysangha** [comment]
How do you see this in the Excel Workbook as another sheet or tacked onto the Firewall Rule sheet?

**Comment by 2cool2touch** [comment]
What's your take. I see usecase in both ways - it may come down to ease of coding too.

**Sheet of its own:**
If its a sheet of its own, like Partner Security Services, it would be consistent with the UI.

In small environment, putting them together may work but in large env, it may cause confusion.

**Merged - Single Sheet with Both:**
On the other hand, putting them together could be really useful. Mostly, the question I get is I want to see if the DFW rule is allowing it or not and then i check Redirect rule. Today, to do that, I have to go to the General Tab and then find corresponding policy in Partner tab. 

Putting them together makes the sheet even more useful compared to UI. We can say, we put the L3Rule and Redirect rules in one view so you know exactly how the packet is processed.

------
The above was me thinking out loud. I like the second story better.

Your thoughts?

**Comment by HammadAlam** [comment]
This is completed and merged to master. Thanks @tonysangha for the quick turnaround
