### ISSUE TITLE
 .xml healthcheck  out put to HTML 

### ISSUE THREAD

**Issue by kakollu007** [vmware/nsx-powerops#59]
Could anyone suggest me how to convert  .xml helthcheck output to HTML format ?

**Comment by HammadAlam** [comment]
The .xml file was generated so the user has a record of a healthcheck run. When the user navigates away from the screen or tries to remember what the result was, they can refer to it. We were not expecting this to be more then that. Can you help us understand how you are using it and we can think about automating it.

Just to convert, you can use something like https://www.xmlfox.com.

Feel free to connect offline  to discuss in detail. halam at vmware
