### ISSUE TITLE
Add a way to disconnect from current connection and connect using a different profile

### ISSUE THREAD

**Issue by HammadAlam** [vmware/nsx-powerops#64]
Under Connection Profiles, Add a way to disconnect from current connection and connect using a different profile

disconnect-viserver
disconnect-nsxserver

Currently the only way is to change the default profile to use different connections.

**Comment by HammadAlam** [comment]
Proposed changes

a. Change the menu name from Configure Connection Profiles to just Connection Profiles
b. Add an option to List Connection Profiles
c. Add a way to disconnect from currently connected profile to a different profile

**Comment by thisispuneet** [comment]
Following are the content from ticket #35 (similar tickets merging both)

> Once you start the tool and if you chose not to auto connect or it failed for some reason. We need a way from within the tool to kickstart connection again.
> 
> In addition, if you are connected using a profile, but would like to connect using a different (non-default profile). There should be a way to switch the profile and connect using that without exiting.
> 
> May be we can add a #-4 in the Connection Profiles which says connect to selected profile.
> 
> This can also be useful if from within the tool you want to disconnect and then connect to a new profile that was just created.
> 
> May be there is a way but is not obvious.
