### ISSUE TITLE
[Urgent] Rename the VTEP to VTEP single host user input

### ISSUE THREAD

**Issue by HammadAlam** [vmware/nsx-powerops#73]
Currently, when the  VTEP to VTEP test is run for single host, it asks the user:

>> Please provide the Host ID:

It gives the impression that you have to enter the MOID of the Host from vCenter. In reality it needs the name or IP used by vCenter to add the host to the vCenter. So if the ESXi host is added to vCenter with name for ex, 63esxcomp1.powerops.local then that needs to be the input. If the host is added to vCenter using the management IP of the host then that needs to be entered here.

We need to update the wording to something like:

>> Please provide the name/ip used to add the ESXi host to vCenter:

**Comment by thisispuneet** [comment]
commit bec5a4c4addee1f7c2ea9e562944bcc26348e3d3 updated it.
Case Closed.
